from enum import Enum


class HumanVectorState(str, Enum):
    SESSION_CREATED = "SESSION_CREATED"
    SESSION_CANCELLED = "SESSION_CANCELLED"

    DIRECTION_DRAFT = "DIRECTION_DRAFT"
    DIRECTION_VALIDATION_REQUIRED = "DIRECTION_VALIDATION_REQUIRED"
    DIRECTION_CONFIRMATION_REQUIRED = "DIRECTION_CONFIRMATION_REQUIRED"
    DIRECTION_LOCKED = "DIRECTION_LOCKED"

    BUILDER_V1_PACKAGE_PREPARATION = "BUILDER_V1_PACKAGE_PREPARATION"
    BUILDER_V1_READY = "BUILDER_V1_READY"
    BUILDER_V1_RUNNING = "BUILDER_V1_RUNNING"
    V1_GENERATED = "V1_GENERATED"

    HUMAN_RESPONSE_REQUIRED = "HUMAN_RESPONSE_REQUIRED"
    HUMAN_RESPONSE_DRAFT = "HUMAN_RESPONSE_DRAFT"
    HUMAN_RESPONSE_CONFIRMATION_REQUIRED = "HUMAN_RESPONSE_CONFIRMATION_REQUIRED"
    HUMAN_RESPONSE_CAPTURED = "HUMAN_RESPONSE_CAPTURED"

    CRITIC_PACKAGE_PREPARATION = "CRITIC_PACKAGE_PREPARATION"
    CRITIC_READY = "CRITIC_READY"
    CRITIC_RUNNING = "CRITIC_RUNNING"
    CRITIC_REVIEW_GENERATED = "CRITIC_REVIEW_GENERATED"
    CONFLICT_SPACE_READY = "CONFLICT_SPACE_READY"

    HUMAN_CRITIC_SELECTION = "HUMAN_CRITIC_SELECTION"
    CRITIC_CLARIFICATION_REQUIRED = "CRITIC_CLARIFICATION_REQUIRED"

    MANUAL_TRANSFER_PREPARATION = "MANUAL_TRANSFER_PREPARATION"
    MANUAL_TRANSFER_IN_PROGRESS = "MANUAL_TRANSFER_IN_PROGRESS"
    TRANSFER_CONFIRMATION_REQUIRED = "TRANSFER_CONFIRMATION_REQUIRED"
    TRANSFER_PACKAGE_LOCKED = "TRANSFER_PACKAGE_LOCKED"

    MEMORY_RETRIEVAL_READY = "MEMORY_RETRIEVAL_READY"
    MEMORY_RETRIEVAL_RUNNING = "MEMORY_RETRIEVAL_RUNNING"
    MEMORY_REVIEW_REQUIRED = "MEMORY_REVIEW_REQUIRED"
    MEMORY_SELECTION_CONFIRMATION_REQUIRED = "MEMORY_SELECTION_CONFIRMATION_REQUIRED"
    MEMORY_SELECTION_LOCKED = "MEMORY_SELECTION_LOCKED"
    NO_RELEVANT_MEMORY = "NO_RELEVANT_MEMORY"

    RECONSTRUCTION_PACKAGE_PREPARATION = "RECONSTRUCTION_PACKAGE_PREPARATION"
    RECONSTRUCTION_PACKAGE_CONFIRMATION_REQUIRED = "RECONSTRUCTION_PACKAGE_CONFIRMATION_REQUIRED"
    RECONSTRUCTION_PACKAGE_READY = "RECONSTRUCTION_PACKAGE_READY"
    RECONSTRUCTION_RUNNING = "RECONSTRUCTION_RUNNING"
    VN_GENERATED = "VN_GENERATED"

    VERSION_COMPARISON_READY = "VERSION_COMPARISON_READY"
    VERSION_COMPARISON_GENERATED = "VERSION_COMPARISON_GENERATED"
    HUMAN_VERIFICATION_REQUIRED = "HUMAN_VERIFICATION_REQUIRED"
    ITERATION_DECISION_REQUIRED = "ITERATION_DECISION_REQUIRED"

    DIRECTION_REVISION_REQUIRED = "DIRECTION_REVISION_REQUIRED"
    BRANCH_CREATION_REQUIRED = "BRANCH_CREATION_REQUIRED"
    BRANCH_CREATED = "BRANCH_CREATED"

    VF_CONFIRMATION_REQUIRED = "VF_CONFIRMATION_REQUIRED"
    VF_HUMAN_DECLARATION = "VF_HUMAN_DECLARATION"
    VF_DECLARED = "VF_DECLARED"
    VF_LOCKING_IN_PROGRESS = "VF_LOCKING_IN_PROGRESS"
    VF_LOCKED = "VF_LOCKED"

    FINAL_REPORT_GENERATION = "FINAL_REPORT_GENERATION"
    FINAL_REPORT_READY = "FINAL_REPORT_READY"
    SESSION_ARCHIVED = "SESSION_ARCHIVED"

    SESSION_PAUSED = "SESSION_PAUSED"
    TECHNICAL_ERROR = "TECHNICAL_ERROR"
    AI_OPERATION_FAILED = "AI_OPERATION_FAILED"
    MEMORY_RETRIEVAL_FAILED = "MEMORY_RETRIEVAL_FAILED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"


ALL_STATE_ORDER = tuple(HumanVectorState)

MAIN_PATH_STATE_ORDER = (
    HumanVectorState.SESSION_CREATED,
    HumanVectorState.DIRECTION_DRAFT,
    HumanVectorState.DIRECTION_VALIDATION_REQUIRED,
    HumanVectorState.DIRECTION_CONFIRMATION_REQUIRED,
    HumanVectorState.DIRECTION_LOCKED,
    HumanVectorState.BUILDER_V1_RUNNING,
    HumanVectorState.V1_GENERATED,
    HumanVectorState.HUMAN_RESPONSE_REQUIRED,
    HumanVectorState.HUMAN_RESPONSE_CAPTURED,
    HumanVectorState.CRITIC_RUNNING,
    HumanVectorState.CONFLICT_SPACE_READY,
    HumanVectorState.HUMAN_CRITIC_SELECTION,
    HumanVectorState.MANUAL_TRANSFER_IN_PROGRESS,
    HumanVectorState.TRANSFER_PACKAGE_LOCKED,
    HumanVectorState.MEMORY_RETRIEVAL_READY,
    HumanVectorState.MEMORY_RETRIEVAL_RUNNING,
    HumanVectorState.MEMORY_REVIEW_REQUIRED,
    HumanVectorState.MEMORY_SELECTION_CONFIRMATION_REQUIRED,
    HumanVectorState.MEMORY_SELECTION_LOCKED,
    HumanVectorState.NO_RELEVANT_MEMORY,
    HumanVectorState.RECONSTRUCTION_PACKAGE_PREPARATION,
    HumanVectorState.RECONSTRUCTION_PACKAGE_CONFIRMATION_REQUIRED,
    HumanVectorState.RECONSTRUCTION_PACKAGE_READY,
    HumanVectorState.RECONSTRUCTION_RUNNING,
    HumanVectorState.VN_GENERATED,
    HumanVectorState.VERSION_COMPARISON_GENERATED,
    HumanVectorState.HUMAN_VERIFICATION_REQUIRED,
    HumanVectorState.VF_CONFIRMATION_REQUIRED,
    HumanVectorState.VF_HUMAN_DECLARATION,
    HumanVectorState.VF_DECLARED,
    HumanVectorState.VF_LOCKED,
    HumanVectorState.FINAL_REPORT_READY,
    HumanVectorState.SESSION_ARCHIVED,
)

assert len(ALL_STATE_ORDER) == 56
assert len(MAIN_PATH_STATE_ORDER) == 33
